### ISSUE TITLE
Ошибка в кодировке при считывании файла

### ISSUE THREAD

**Issue by sheriff1max** [ai-forever/augmentex#18]
![image](https://github.com/ai-forever/augmentex/assets/74362240/a8b37d28-805c-4a84-a805-134680a65873)

На моём пк такая проблема, можете, пожалуйста, добавить в файл base.py при открытии файла encoding='utf-8'? 48 строка кода.

**Comment by OZheRelieV** [comment]
Аналогичная ошибка сразу вылетает при инициализации класса WordAug:

word_aug = WordAug(
    unit_prob=0.4, # Percentage of the phrase to which augmentations will be applied
    min_aug=1, # Minimum number of augmentations
    max_aug=5, # Maximum number of augmentations
    lang="eng", # supports: "rus", "eng"
    platform="pc", # supports: "pc", "mobile"
    random_seed=42,
)
